jobs:
  - name: major
    serial: true
    plan:
      - in_parallel:
          limit: 2
          steps:
            - get: eloqkv_src
              params:
                submodules: all
            - get: base_image
      - task: new-tag
        image: base_image
        params:
          TAG_LEVEL: "major"
          GIT_SSH_KEY: ((git-key))
        file: eloqkv_src/concourse/tasks/tag.yml
  - name: minor
    serial: true
    plan:
      - in_parallel:
          limit: 2
          steps:
            - get: eloqkv_src
              params:
                submodules: all
            - get: base_image
      - task: new-tag
        image: base_image
        params:
          TAG_LEVEL: "minor"
          GIT_SSH_KEY: ((git-key))
        file: eloqkv_src/concourse/tasks/tag.yml
  - name: patch
    serial: true
    plan:
      - in_parallel:
          limit: 2
          steps:
            - get: eloqkv_src
              params:
                submodules: all
            - get: base_image
      - task: new-tag
        image: base_image
        params:
          TAG_LEVEL: "patch"
          GIT_SSH_KEY: ((git-key))
        file: eloqkv_src/concourse/tasks/tag.yml

resources:
  - name: base_image
    source:
      repository: eloqdata/eloq-dev-ci-ubuntu2404
    type: registry-image

  - name: eloqkv_src
    source:
      branch: main
      private_key: ((git-key))
      uri: git@github.com:eloqdata/eloqkv.git
    type: git
